[theme]
base = "light"
primaryColor = "#004643"
backgroundColor = "#F0EDE5"
secondaryBackgroundColor = "#e5e7eb"
textColor = "#004643"
font = "sans serif"

[server]
headless = true
port = 8501

[browser]
gatherUsageStats = false
